# Generated by Django 3.0.4 on 2020-04-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='created_at',
        ),
    ]
