# Generated by Django 3.0.4 on 2020-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_data_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploads_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='Profile_pics')),
                ('img_name', models.CharField(default='', max_length=100)),
                ('img_city', models.CharField(max_length=100)),
            ],
        ),
    ]
