# Generated by Django 3.0.4 on 2020-04-07 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uploads_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads_slider',
            name='uploded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
